#!/bin/env python3

# =========================================================================
# Copyright (C) 2022 Pavol Federl (pfederl@ucalgary.ca)
# All Rights Reserved. Do not distribute this file.
# =========================================================================
# DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

import sys

def main():
    max_pali = b""
    while True:
        line = sys.stdin.buffer.readline()
        if len(line) == 0: break
        words = line.split()
        for word in words:
            if len(word) <= len(max_pali):
                continue
            if word.lower() == word.lower()[::-1]:
                max_pali = word
    sys.stdout.buffer.write(b"Longest palindrome: ")
    sys.stdout.buffer.write(max_pali)
    sys.stdout.buffer.write(b"\n")

main()
